# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 01:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
