# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_auto_20160422_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Project name')),
            ],
        ),
        migrations.AlterModelManagers(
            name='permission',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
