# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_auto_20160423_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='permission',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project', 'Ver detalles'),)},
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
