# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_auto_20160423_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': (('add_project', 'Crea un projecto y asigna el "Scrum Master".'), ('delete_project', 'Elimina un projecto.'), ('view_project_details', 'Ver detalles del projecto.'), ('view_kanbam', 'Ver Kanbam.'))},
        ),
    ]
