# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_auto_20160423_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Role',
        ),
    ]
