# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0008_auto_20160423_2230'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
