# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '__first__'),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, verbose_name='Project name')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('development_team', models.ManyToManyField(related_name='mm_project_development_team', to='autenticacion.User')),
                ('product_backlog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.ProductBacklog')),
                ('product_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_project_product_owner', to='autenticacion.User')),
                ('scrum_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_project_scrum_master', to='autenticacion.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='developmentTeam',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='productBacklog',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='productOwner',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='scrumMaster',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='sprintBacklog',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='sprint',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='SprintBacklog',
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Project'),
        ),
    ]
