# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20160501_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('details', models.TextField()),
                ('acceptance_requirements', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('business_value', models.FloatField()),
                ('tecnical_value', models.FloatField()),
                ('urgency', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.UserStory')),
            ],
        ),
        migrations.AlterModelManagers(
            name='productbacklog',
            managers=[
                ('productbacklogs', django.db.models.manager.Manager()),
            ],
        ),
    ]
