# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20160505_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='backlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.ProductBacklog'),
        ),
    ]
