# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('proyecto', '__first__'),
        ('administracion', '0004_userstory_backlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.User')),
            ],
            managers=[
                ('notes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='development_team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='product_backlog',
        ),
        migrations.RemoveField(
            model_name='project',
            name='product_owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scrum_master',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userstorynote',
            name='user_story',
        ),
        migrations.AlterModelManagers(
            name='userstory',
            managers=[
                ('user_stories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='backlog',
        ),
        migrations.AddField(
            model_name='userstory',
            name='allowed_developers',
            field=models.ManyToManyField(to='autenticacion.User'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Project'),
        ),
        migrations.DeleteModel(
            name='ProductBacklog',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Sprint',
        ),
        migrations.DeleteModel(
            name='UserStoryNote',
        ),
        migrations.AddField(
            model_name='note',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.UserStory'),
        ),
        migrations.AddField(
            model_name='grained',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Sprint'),
        ),
        migrations.AddField(
            model_name='grained',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.UserStory'),
        ),
    ]
