# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('productBacklog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.ProductBacklog')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sprintBacklog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.SprintBacklog'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(to='administracion.Usuario'),
        ),
    ]
