# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20160424_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='developmentTeam',
            field=models.ManyToManyField(related_name='asdff', to='administracion.Usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='productOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asdfa', to='administracion.Usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='scrumMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asdf', to='administracion.Usuario'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='sprintBacklog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.SprintBacklog'),
        ),
    ]
